/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_form;

import SystemNpruPool.Register;
import SystemNpruPool.Staff;
import SystemNpruPool.User;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Boss
 */
public class course_swim extends javax.swing.JFrame {
        User u =new User();

        Staff st =new Staff();

    /**
     * Creates new form course_swim
     */
    public course_swim() {
        initComponents();
        u.CheckUser(u.getU_Id());
             System.out.println("u id on  swim_pool= "+u.getU_Id());
                System.out.println("st id on befor swim_pool= "+st.getSt_Id());
           st.CheckStaff(st.getSt_Id());
           System.out.println("st id on after swim_pool= "+st.getSt_Id());
           st.CheckLogin(st.getSt_Id(),st.getSt_Password());
            out_uid.setText(String.valueOf(u.getU_Id()));
            out_ubirthday.setText(u.getU_Birthday());
          
            out_ufirstname.setText(u.getU_Firstname());
            out_ulastname.setText(u.getU_Lastname());
       out_uage.setText(String.valueOf(u.getU_Age()));
       if(in_c1.isSelected()){
             out_pricecourse.setText("90 บาท");
       }
       else if(in_c2.isSelected()){
              out_pricecourse.setText("95 บาท");
       }
         
    }
      public void close(){
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btn_course_swim = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        out_uid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        out_ufirstname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        out_ulastname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        out_ubirthday = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        out_uage = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        in_c1 = new javax.swing.JButton();
        in_c2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        out_pricecourse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Swimming-52.png"))); // NOI18N
        jLabel1.setText("ชำระค่าสมัครเรียนคอร์สว่ายน้ำ");

        btn_course_swim.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btn_course_swim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/File-complete-icon.png"))); // NOI18N
        btn_course_swim.setText("เสร็จสิ้น");
        btn_course_swim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_course_swimActionPerformed(evt);
            }
        });

        btn_menu.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon.png"))); // NOI18N
        btn_menu.setText("กลับหน้าหลัก");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel4.setText("รหัสสมาชิก");

        out_uid.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        out_uid.setText("............................");

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel2.setText("ชื่อ");

        out_ufirstname.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        out_ufirstname.setText("............................");

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel3.setText("นามสกุล");

        out_ulastname.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        out_ulastname.setText(".............................");

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel5.setText("วัน / เดือน / ปี เกิด");

        out_ubirthday.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        out_ubirthday.setText(".............................");

        jLabel8.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel8.setText("อายุ");

        out_uage.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        out_uage.setText(".............................");

        jLabel12.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel12.setText("กรุณาเลือคอร์สที่ต้องการ");

        in_c1.setText("คอร์สสอนว่ายน้ำสำหรับผู้มีอายุไม่เกิน 12 ปี");
        in_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_c1ActionPerformed(evt);
            }
        });

        in_c2.setText("คอร์สสอนว่ายน้ำสำหรับผู้มีอายุมากกว่า 12 ปี");
        in_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_c2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel13.setText("ราคา");

        out_pricecourse.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        out_pricecourse.setText("...................        บาท");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(out_ufirstname)
                            .addComponent(out_uid)
                            .addComponent(out_ulastname)
                            .addComponent(out_ubirthday)
                            .addComponent(out_uage)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_c2)
                            .addComponent(in_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(out_pricecourse)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(out_uid))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(out_ufirstname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(out_ulastname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(out_ubirthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(out_uage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_c1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_c2)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(out_pricecourse)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_course_swim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_menu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_course_swim))
                .addGap(25, 25, 25))
        );

        getAccessibleContext().setAccessibleName("สมัครเรียนคอร์สเรียนว่ายน้ำ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_course_swimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_course_swimActionPerformed
        // TODO add your handling code here:
        Register rg =new Register();
        int money ;
        int c_Id=0  ; 
        if(out_pricecourse.getText().equals("90 บาท")){
        money =90;
            c_Id =1;
             Calendar c = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat df1 = new SimpleDateFormat("HH:mm:ss");
        String currentDate = df.format(c.getTime());//ปีเดือนวัน
        String currentDate1= df1.format(c.getTime());//ปีเดือนวัน+เวลาล
              System.out.println(c_Id);

        rg.InsertRegister(1, currentDate1, currentDate, u.getU_Id(), 1);
                  JOptionPane.showMessageDialog(null,
	    "ทำรายการสำเร็จ.",
	    "",
	    JOptionPane.WARNING_MESSAGE);
                  course_user cu = new course_user();
                  cu.setVisible(true);
                    close();
        }
        else if(out_pricecourse.getText().equals("95 บาท")){
            money = 95;
            c_Id =2;
             Calendar c = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat df1 = new SimpleDateFormat("HH:mm:ss");
        String currentDate = df.format(c.getTime());//ปีเดือนวัน
        String currentDate1= df1.format(c.getTime());//ปีเดือนวัน+เวลาล
              System.out.println(c_Id);

        rg.InsertRegister(1, currentDate1, currentDate, u.getU_Id(), 2);
              JOptionPane.showMessageDialog(null,
	    "ทำรายการสำเร็จ.",
	    "",
	    JOptionPane.WARNING_MESSAGE);
                    course_user cu = new course_user();
                  cu.setVisible(true);
                  
                close();
        }
        else{
                 JOptionPane.showMessageDialog(null,
	    "กรุณาเลือก คอร์สที่ต้องการ.",
	    "โปรดทำรายการใหม่อีกครั้ง.",
	    JOptionPane.WARNING_MESSAGE);
        }
     System.out.println(c_Id);
    }//GEN-LAST:event_btn_course_swimActionPerformed

    private void in_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_c1ActionPerformed
        // TODO add your handling code here:
          
             out_pricecourse.setText("90 บาท");
      
       
    }//GEN-LAST:event_in_c1ActionPerformed

    private void in_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_c2ActionPerformed
        // TODO add your handling code here:
          out_pricecourse.setText("95 บาท");
    }//GEN-LAST:event_in_c2ActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        user u =new user();
           u.setVisible(true);
        close();
    }//GEN-LAST:event_btn_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(course_swim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(course_swim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(course_swim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(course_swim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new course_swim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_course_swim;
    private javax.swing.JButton btn_menu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton in_c1;
    private javax.swing.JButton in_c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel out_pricecourse;
    private javax.swing.JLabel out_uage;
    private javax.swing.JLabel out_ubirthday;
    private javax.swing.JLabel out_ufirstname;
    private javax.swing.JLabel out_uid;
    private javax.swing.JLabel out_ulastname;
    // End of variables declaration//GEN-END:variables
}
